# ========================================
#      Job Ochieng | Portfolio Website
# ========================================

theme: jekyll-theme-chirpy
lang: en
timezone: Africa/Nairobi

title: "Job Ochieng"
tagline: "Engineering Secure, Intelligent, and Sustainable Solutions."
description: >
  A multidisciplinary engineer dedicated to creating technology that drives progress responsibly.
  I combine expertise in cybersecurity, AI, and energy systems to deliver solutions that are both powerful and principled.

url: "https://ochiengjob.github.io"
baseurl: ""

avatar: /assets/jobprofile.png
social_preview_image: /assets/social-card.png

github:
  username: ochiengjob
twitter:
  username: O_chiengjob

social:
  name: Job Ochieng
  email: jobochieng82@gmail.com
  links:
    - https://linkedin.com/in/ochiengjob
    - https://github.com/ochiengjob
    - https://twitter.com/O_chiengjob

theme_mode: dark
toc: true
paginate: 10

pwa:
  enabled: true
  cache:
    enabled: true

comments:
  provider:

analytics:
  google:
    id:

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

  index_redirect: /tabs/home/

